export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const COMPOSING_STATEMENT = "COMPOSING_STATEMENT";
export const USER_REGISTRATION = "USER_REGISTRATION";

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const CHECKLOGINAUTH = "CHECKLOGINAUTH";

export const AUTHCREDENTIALFAIL = "AUTHCREDENTIALFAIL";

export const CKECK_USER_IN = "CKECK_USER_IN";
export const TOGGLE_DROP = "TOGGLE_DROP";

export const PROFILE_TO_STATEMENTS = "PROFILE_TO_STATEMENTS";
export const ON_AUTH_TYPE_CHECKER = "ON_AUTH_TYPE_CHECKER";
export const JWT_SECRET = "myNameIsMurtuzaKavantwala";
export const AUTHCREDENTIALFAIL_MESSAGE = "AUTHCREDENTIALFAIL_MESSAGE";
export const CAPTCHA = "CAPTCHACREATORE";
export const VERIFICATION = "VERIFICATION_OF_USERS";
export const TEXT = "Text_EDITOR";
export const NEW_FINAL_TEXT = "NEW_FINAL_TEXT";

export const ALL_STATEMENTS_DATA = "ALL_STATEMENTS_DATA";
export const SEARCH_FIELDS = "SEARCH_FIELDS";
export const NUMBER_VERIFICATION = "NUMBER_VERIFICATION";
export const RECENT_STATEMENTS = "RECENT_STATEMENTS";
export const USER_LEVEL_CHECK = "USER_LEVEL_CHECK";
export const USER_MENTIONS_FOUND = "USER_MENTIONS_FOUND";
